name: pytestresultsdiff
description: 'Installs and runs pytestresultsdiff on the current runner'
branding:
  icon: package
  color: yellow

inputs:
  results-xmls:
    description: "space-separated filenames of `results.xml` to compare"
    required: true
  time-relative-tolerance:
    description: "fractional tolerance for time deviation [default: 0.1]" 
    required: false
    default: "0.1"
  time-absolute-tolerance:
    description: "absolute tolerance (in seconds) for time deviation [default: 0.1]"
    required: false
    default: "0.1"
  peakmem-relative-tolerance:
    description: "fractional tolerance for peakmem deviation [default: 0.1]" 
    required: false
    default: "0.1"
  peakmem-absolute-tolerance:
    description: "absolute tolerance (in MB) for peakmem deviation [default: 0.1]"
    required: false
    default: "0.1"
  features:
    description: "comma-separated list of crate features: `peakmem,extra-properties,url,system-err,system-out`"
    required: false
    default: "peakmem,extra-properties"
  summary_table_properties:
    description: "space-separated list of properties with which to build a summary table"
    required: false
    default: ""
  output-file:
    description: "filename of JSON to write to"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1 
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: braingram/pytestresultsdiff
        ref: props
        path: ./_pytestresultsdiff/
    - shell: bash
      run: |
        cargo install --path ./_pytestresultsdiff/ --target-dir ~/.cargo/bin/ ${{ inputs.features != '' && format('--features {0}', inputs.features) || '' }}
        echo "~/.cargo/bin/" >> $GITHUB_PATH
        rm -rf ./pytestresultsdiff/
    - id: filename
      shell: bash
      run: echo filename=${{ inputs.output-file != '' && inputs.output-file || format('{0}/resultsdiff.json', runner.temp) }} >> $GITHUB_OUTPUT
    - shell: bash
      run: pytestresultsdiff ${{ inputs.results-xmls }} -m ${{ inputs.peakmem-relative-tolerance }} -M ${{ inputs.peakmem-absolute-tolerance }} -t ${{ inputs.time-relative-tolerance }} -T ${{ inputs.time-absolute-tolerance }} > ${{ steps.filename.outputs.filename }}
    - if: inputs.summary_table_properties != ''
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
    - if: inputs.summary_table_properties != ''
      shell: bash
      run: python scripts/generate_markdown_table.py ${{ steps.filename.outputs.filename }} ${{ inputs.summary_table_properties }} >> $GITHUB_STEP_SUMMARY
    - id: output
      shell: bash
      run: echo output=$(cat ${{ steps.filename.outputs.filename }}) >> $GITHUB_OUTPUT

outputs:
  diff:
    description: "output of pytestresultsdiff"
    value: ${{ steps.output.outputs.output }}
