name: pytestresultsdiff
description: 'Installs and runs pytestresultsdiff on the current runner'
branding:
  icon: package
  color: yellow

inputs:
  results-xmls:
    description: "space-separated filenames of `results.xml` to compare"
    required: true
  time-relative-tolerance:
    description: "fractional tolerance for time deviation [default: 0.1]" 
    required: false
    default: "0.1"
  time-absolute-tolerance:
    description: "absolute tolerance (in seconds) for time deviation [default: 0.1]"
    required: false
    default: "0.1"
  output-file:
    description: "filename of JSON to write to"
    required: false
    default: ""
  features:
    description: "comma-separated list of crate features: `url,system-err,system-out,extra-properties`"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1 
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: zacharyburnett/pytestresultsdiff
        # ref: 3eefa221961ea57b5a08713adb74e3bbbed9ec58 # 0.6.0
        path: ./_pytestresultsdiff/
    - shell: bash
      run: |
        cargo install --path ./_pytestresultsdiff/ --target-dir ~/.cargo/bin/ ${{ inputs.features != '' && format('--features {0}', inputs.features) || '' }}
        echo "~/.cargo/bin/" >> $GITHUB_PATH
        rm -rf ./pytestresultsdiff/
    - id: filename
      shell: bash
      run: echo filename=${{ inputs.output-file != '' && inputs.output-file || format('{0}/resultsdiff.json', runner.temp) }} >> $GITHUB_OUTPUT
    - shell: bash
      run: pytestresultsdiff ${{ inputs.results-xmls }} -r ${{ inputs.time-relative-tolerance }} -a ${{ inputs.time-absolute-tolerance }} > ${{ steps.filename.outputs.filename }}
    - id: output
      shell: bash
      run: echo output=$(cat ${{ steps.filename.outputs.filename }}) >> $GITHUB_OUTPUT

outputs:
  diff:
    description: "output of pytestresultsdiff"
    value: ${{ steps.output.outputs.output }}
