name: pytestresultsdiff
description: 'Installs and runs pytestresultsdiff on the current runner'
inputs:
  results-xmls:
    description: "space-separated filenames of `results.xml` to compare"
    required: true
  time-relative-tolerance:
    description: "fractional tolerance for time deviation [default: 0.1]" 
    required: false
    default: "0.1"
  time-absolute-tolerance:
    description: "absolute tolerance (in seconds) for time deviation [default: 0.1]"
    required: false
    default: "0.1"
outputs:
  diff:
    description: "output of pytestresultsdiff"
    value: ${{ steps.run.outputs.stdout }}
branding:
  icon: package
  color: yellow

runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1 
    - shell: bash
      run: cargo run -- ${{ inputs.results-xmls }} -r ${{ inputs.time-relative-tolerance }} -a ${{ inputs.time-absolute-tolerance }} > resultsdiff.json
    - id: run
      shell: bash
      run: echo "stdout=(cat resultsdiff.json)" >> $GITHUB_OUTPUT
