name: build

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1 
      - run: cargo build --release
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x target/release/pytestresultsdiff
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: ${{ runner.os }}
          path: target/release/pytestresultsdiff${{ runner.os == 'Windows' && '.exe' || '' }}
