name: build

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - if: runner.os == 'Linux'
        run: sudo apt install -y pkg-config libusb-1.0-0-dev libftdi1-dev libudev-dev
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1 
      - run: cargo build --release
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x target/release/pytestresultsdiff
      - uses: vimtor/action-zip@1379ea20d4c5705669ba81fd626dd01b1c738f26 # v1.2
        with:
          files: target/release/pytestresultsdiff${{ runner.os == 'Windows' && '.exe' || '' }}
          dest: ${{ runner.os }}.zip
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: ${{ runner.os }}
          path: target/release/pytestresultsdiff${{ runner.os == 'Windows' && '.exe' || '' }}
      - if: (github.event_name == 'release' && github.event.action == 'published')
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
        with:
          file: ${{ runner.os }}.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
