name: test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-binary:
    name: cargo test
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-13
          - macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
      - run: cargo test
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a:
          - ./src/data/time/romancal_24Q4_B15.0.0_results-Linux-x64-py3.11.xml
          - ./src/data/peakmem/main.xml
        b:
          - ./src/data/time/romancal_nightly_results-Linux-x64-py3.11.xml
          - ./src/data/peakmem/pr.xml
          - ./src/data/peakmem/main.xml
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          results-xmls: >-
            ${{ matrix.a }}
            ${{ matrix.b }}
          time-absolute-tolerance: 0.2
          peakmem-absolute-tolerance: 1
          summary-table-properties: status time peakmem
          output-file: resultsdiff.json
      - run: cat resultsdiff.json
