name: test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254 # v3.2.0
        with:
          version: "0.4.28"
          enable-cache: true
      - run: uv venv
      - run: uv pip install .[test]
      - run: uv run pytest .
      - run: uv cache prune --ci
